---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, setoptions, echo = TRUE}
activity <- read.csv("activity.csv", colClasses = c("numeric", "factor" , "numeric"))
activity$date <- as.Date(strptime(activity$date, "%Y-%m-%d"))
```

## What is mean total number of steps taken per day?

```{r}
library(ggplot2)
ggplot(activity, aes(x=date,y=steps)) + geom_histogram(stat="identity")
means_table <- aggregate(list (steps=activity$steps[!is.na(activity$steps)]), by = list (date=activity$date[!is.na(activity$steps)]), mean, na.rm=TRUE)
medians_table <- aggregate(list (steps=activity$steps[!is.na(activity$steps)]), by = list (date=activity$date[!is.na(activity$steps)]), median, na.rm=TRUE)
means_table <- aggregate(list (steps=activity$steps), by = list (date=activity$date), mean, na.rm=TRUE)
medians_table <- aggregate(list (steps=activity$steps), by = list (date=activity$date), median, na.rm=TRUE)
means_table
medians_table
```



## What is the average daily activity pattern?
```{r}
means2_table <- aggregate(list (steps=activity$steps[!is.na(activity$steps)]), by = list (interval=activity$interval[!is.na(activity$steps)]), mean, na.rm=TRUE)
plot(means2_table$interval, means2_table$steps, type="l", ylab="Mean steps", xlab="Interval")
max = means2_table$interval[means2_table$steps==max(means2_table$steps)]
paste("The 5-minute interval that contains the maximum number of steps is :", max)
```

## Imputing missing values
```{r}
sapply(activity, function(x) sum(is.na(x)))
for (i in 1:nrow(activity)) {
  if (is.na(activity[i, "steps"])) {
    if (is.na(means_table$steps[means_table$date==activity[66, "date"]])) {
      activity[i, "steps"] <- 0
    } else {
      activity[i, "steps"] <- means_table$steps[means_table$date==activity[66, "date"]]
    }
  }
}
sapply(activity, function(x) sum(is.na(x)))
ggplot(activity, aes(x=date,y=steps)) + geom_histogram(stat="identity")
means_table <- aggregate(list (steps=activity$steps), by = list (date=activity$date), mean, na.rm=TRUE)
medians_table <- aggregate(list (steps=activity$steps), by = list (date=activity$date), median, na.rm=TRUE)
means_table
medians_table
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity$day <- as.POSIXlt(activity$date)$wday
subset_weekdays <- sub <- subset(activity, day <= 5)
subset_weekends <- sub <- subset(activity, day >= 6)
means2_weekdays <- aggregate(list (steps=subset_weekdays$steps[!is.na(subset_weekdays$steps)]), 
      by = list (interval=subset_weekdays$interval[!is.na(subset_weekdays$steps)]), mean, na.rm=TRUE)
means2_weekends <- aggregate(list (steps=subset_weekends$steps[!is.na(subset_weekends$steps)]),
      by = list (interval=subset_weekends$interval[!is.na(subset_weekends$steps)]), mean, na.rm=TRUE)
par(mfrow = c(2,1)) 
plot(means2_weekdays$interval, means2_weekdays$steps, type="l", ylab="Number of steps", xlab="Interval", main="Weekdays")
plot(means2_weekends$interval, means2_weekends$steps, type="l", ylab="Number of steps", xlab="Interval", main="Weekends")
```

